### PR TITLE
Client-side, submitted ticket.

### PR DESCRIPTION
**Pull request by tenko23**
Believe I have it this time - see how it goes :) ~

### CODE REVIEW

**Comment by tenko23** [comment]
before
fix

^ Before/after.

**Comment by tenko23** [comment]
Colorizing fonts & icons... changing entry box font color from gray to black.

Before:
before1
before2

After:
after1
after2

**Comment by tenko23** [comment]
^ This is on the agent side.

**Comment by TheStrato** [comment]
@HPringles Can you have one last look at all this and the other PR before I merge them?

**Comment by HPringles** [comment]
All good

**Pull request merged**
