### PR TITLE
Merge - redo... css text.

### PR DESCRIPTION
**Pull request by tenko23**
Take 2 - see is HPringles thinks it's ok ;o ~

### CODE REVIEW

**Comment by tenko23** [comment]
Before/after... the blue "after" text is what I'm aiming for right now... hoping to find the bottom one later....

screen shot 2018-04-14 at 5 38 20 pm
screen shot 2018-04-14 at 5 38 20 pm copy

**Comment by tenko23** [comment]
Client.

**Comment by TheStrato** [comment]
The file you edited here is not the client side file. That would be in assests/default/css/theme.css

**Comment by tenko23** [comment]
Ah, ok... might have been some miscommunication, sorry ;o .  Which file do I need to edit?

**Comment by TheStrato** [comment]
assests/default/css/theme.css

**Comment by tenko23** [comment]
Ok, maybe that's why I couldn't find the other change ;p .  I will try again - sorry ;o ~

**Comment by TheStrato** [comment]
It's okay.

**Pull request closed without merging**
